#define pokedexCSV "Ressources/pokedex.csv"
#define TasteBreadHD "Ressources/Fonts/Taste Bread HD.otf"
#define GoldyBurst "Ressources/Fonts/Goldy Burst.ttf"
#define PokemonFont "Ressources/Fonts/Pokemon Classic.ttf"
#define ExploreBackground "Ressources/background.jpeg"